[package]
name = "brick"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.102"
quote = "1.0.41"
syn = { version = "2.0.108", features = ["full"] }

[dev-dependencies]
chrono = "0.4.38"
